language: node_js
node_js:
  - "stable"
script:
  - npm install
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: $KEY
  app: ci-practice
  on:
    repo: CamiloRincon/ci